AllCops:
  Excludes:
    - bin/**
    - db/**
    - vendor/**

Documentation:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Enabled: true
  Max: 140

MethodLength:
  Enabled: true
  Max: 30
