common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['USER'] %>

development:
  <<: *common
  database: releaser_development
  pool: 5

test: &test
  <<: *common
  database: releaser_test
  pool: 1

acceptance:
  <<: *test
